routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
], function()
{
    Route::get('/', function () {
        return view('main.index');
    });

    Route::post('/image/upload', 'ImageController@upload')->name('image.upload');

    Route::group(['prefix'=>'admin', 'as' => 'admin.', 'namespace'=>'Admin', 'middleware'=>['auth', 'can:admin-panel']], function(){
        Route::get('/', 'DashboardController@dashboard')->name('admin.index');

        Route::get('users', 'UserController@index')->name('users.index');

        //Routes for profile
        Route::get('profile', 'ProfileController@index')->name('profile.index');
        Route::get('profile/edit', 'ProfileController@edit')->name('profile.edit');
        Route::put('profile/', 'ProfileController@update')->name('profile.update');

        //Routes for categories
        Route::get('categories', 'CategoryController@index')->name('categories.index');
        Route::get('categories/create', 'CategoryController@create')->name('categories.create');
        Route::post('categories', 'CategoryController@store')->name('categories.store');
        Route::get('categories/{category}/edit', 'CategoryController@edit')->name('categories.edit');
        Route::put('categories/{category}', 'CategoryController@update')->name('categories.update');
        Route::delete('categories/{category}', 'CategoryController@destroy')->name('categories.destroy');

        //Routes for parent-categories
        Route::get('parent-categories', 'ParentCategoryController@index')->name('parent-categories.index');
        Route::get('parent-categories/create', 'ParentCategoryController@create')->name('parent-categories.create');
        Route::post('parent-categories', 'ParentCategoryController@store')->name('parent-categories.store');
        Route::get('parent-categories/{category}/edit', 'ParentCategoryController@edit')->name('parent-categories.edit');
        Route::put('parent-categories/{category}', 'ParentCategoryController@update')->name('parent-categories.update');
        Route::delete('parent-categories/{category}', 'ParentCategoryController@destroy')->name('parent-categories.destroy');

        //Routes for animals
        Route::get('animals', 'AnimalController@index')->name('animals.index');
        Route::get('animals/create', 'AnimalController@create')->name('animals.create');
        Route::post('animals', 'AnimalController@store')->name('animals.store');
        Route::get('animals/{animal}/show', 'AnimalController@show')->name('animals.show');
        Route::get('animals/{animal}/edit', 'AnimalController@edit')->name('animals.edit');
        Route::put('animals/{animal}', 'AnimalController@update')->name('animals.update');
        Route::delete('animals/{animal}', 'AnimalController@destroy')->name('animals.destroy');
        Route::get('animals/download/{id}','AnimalController@download')->name('animals.download');

        Route::get('user-animals', 'AnimalController@UserAnimals')->name('user.animals.ajax');
    });



});
Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

app/Models/ParentCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ParentCategory extends Model
{
    protected $table = 'parent_categories';
    protected $guarded = [];

//    protected $fillable = [
//        'title',
//        'parent_id',
//    ];

    public function children()
    {
        return $this->hasMany(self::class, 'parent_id');
    }
}

app/Http/Controllers/Admin/ParentCategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;
use App\Models\ParentCategory;

class ParentCategoryController extends Controller
{
    public function index()
    {
        $categories = ParentCategory::query()->paginate(20);
        return view('admin.parent-categories.index', [
            'categories' => $categories,
        ]);
    }

    public function create()
    {
        return view('admin.parent-categories.create', [
            'category' =>  [],
            'categories' => ParentCategory::with('children')->where('parent_id', 0)->get(),
            'delimiter' => ''
        ]);
    }

    public function store(Request $request)
    {
        ParentCategory::create($request->all());

        return redirect()->route('admin.parent-categories.index');
    }

    public function show(ParentCategory $category)
    {

    }

    public function edit(ParentCategory $category)
    {
        return view('admin.parent-categories.edit', [
            'category' =>  $category,
            'categories' => ParentCategory::with('children')->where('parent_id', 0)->get(),
            'delimiter' => ''
        ]);
    }

    public function update(Request $request, ParentCategory $category)
    {
        $category->update($request->all());

        return redirect()->route('admin.parent-categories.index');
    }
}

resources/views/admin/parent-categories/create.blade.php
@extends('adminlte::page')

@section('content_header')
    <h1>{{ trans('category.create') }}</h1>
@stop

@section('content')
    {!! Form::open(['url' => route('admin.parent-categories.store')]) !!}
     @include('admin.parent-categories.partials.form', ['mode' => 'create'])
    {!! Form::close() !!}
@stop

resources/views/admin/parent-categories/edit.blade.php
@extends('adminlte::page')

@section('content_header')
    <h1>{{ trans('category.edit') }}</h1>
@stop

@section('content')
    {!! Form::model($category, ['url' => route('admin.parent-categories.update', $category), 'method' => 'POST' ]) !!}
    <input name="_method" type="hidden" value="PUT">
    @include('admin.parent-categories.partials.form', ['mode' => 'edit'])
    {!! Form::close() !!}
@stop

resources/views/admin/parent-categories/index.blade.php
@extends('adminlte::page')

@section('content_header')
    <h1>Под {{ trans('category.title') }}</h1>
@stop

@section('content')
    @if (Session::has('message'))
        <div class="alert alert-info">{{ Session::get('message') }}</div>
    @endif
    <div class="box box-primary">
        <div class="box-header with-border">
            <div class="page-actions">
                <a href="{{ route('admin.parent-categories.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> {{ trans('category.new') }}</a>
            </div>
        </div>
        <br>
        <div class="box-body">
{{--            <form action="{{ route('admin.categories.index') }}">--}}
{{--                <div class="form-group" style="margin-top: 20px;">--}}
{{--                    <div class="input-group">--}}
{{--                        <input type="text" name="search" class="form-control" placeholder="{{  $filter->search !=null ? $filter->search : 'Поиск...' }}" style="border-color: #ccc">--}}
{{--                        <span class="input-group-btn">--}}
{{--                            <button class="btn btn-flat" type="submit" style="border-color: #ccc"><i class="fa fa-search"></i></button>--}}
{{--                        </span>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--            </form>--}}
            <table class="table table-hover table-striped no-margin">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>{{ trans('category.name') }}</th>
                    <th>{{ trans('category.events') }}</th>
                </tr>
                </thead>
                <tbody class="sortable" id="sortable">
                @if (isset($categories))
                    @foreach ($categories as $category)
                        <tr>
                            <td>{{ $category->id }}</td>
                            <td>{{ $category->title }}</td>
                            <td>
                                @if(Auth::user()->can('admin-panel'))
                                    <a class="btn btn-primary btn-sm"
                                       title="Редактировать"
                                       href="{{ route('admin.parent-categories.edit', $category->id) }}"
                                       data-toggle="tooltip"
                                       data-placement="top">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                @endif

                                @if(Auth::user()->can('admin-panel'))
                                    {!! Form::open([
                                           'method' => 'DELETE',
                                           'url' => [route('admin.categories.destroy', $category->id)],
                                           'style' => 'display:inline'
                                       ]) !!}
                                    {!! Form::button('<i class="fa fa-trash" aria-hidden="true"></i>', array(
                                            'type' => 'submit',
                                            'class' => 'btn btn-danger btn-sm',
                                            'title' => 'Удалить жанр',
                                            'onclick'=>'return confirm("Вы действительно хотите удалить?")'
                                    )) !!}
                                    {!! Form::close() !!}
                                @endif
                            </td>
                        </tr>
                    @endforeach
                @endif
                </tbody>
            </table>
            <div style="display: flex; justify-content: center">
                {{ $categories->links() }}
            </div>
        </div>
    </div>
@stop